version: 2.1

commands:
  restore-gradle-cache:
    steps:
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-

  save-gradle-cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    parameters:
      checkout-method:
        type: string
        default: full
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout:
          method: << parameters.checkout-method >>
      - restore-gradle-cache
      - run: ./gradlew build
      - save-gradle-cache

  step-rerun:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - restore-gradle-cache
      - run:
          command: ./gradlew run --args="rerun"
          max_auto_reruns: 3
          auto_rerun_delay: 15s
      - save-gradle-cache

  workflow-rerun:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - restore-gradle-cache
      - run:
          command: ./gradlew run --args="workflowRerun"
      - save-gradle-cache

workflows:
  full-checkout:
    jobs:
      - build

  blobless-checkout:
    jobs:
      - build:
          checkout-method: blobless

  with-step-rerun:
    jobs:
      - step-rerun

  with-workflow-rerun:
    max_auto_reruns: 5
    jobs:
      - workflow-rerun